Upgrades and fixes
allaboutapps/A3AndroidTemplate pull request #42
Opened 2020-09-22 18:35 UTC by geworfener

2020-09-23 11:22 UTC, mgursch requested changes

2020-09-23 11:22 UTC, mgursch commented on {{cookiecutter.repo_name}}/buildSrc/src/main/kotlin/at/allaboutapps/build/Dependencies.kt
> +    const val RetrofitAdapterRxJava = "com.squareup.retrofit2:adapter-rxjava3:${Versions.Retrofit}"
sollte auf jeden Fall RetrofitAdapterRxJava3 heißen

2020-09-23 11:22 UTC, mgursch commented on {{cookiecutter.repo_name}}/app/build.gradle
> -        sourceCompatibility JavaVersion.VERSION_1_8
a) warum löschen wir das 
b)warum bleibt das kommentar darüber stehen, was da natürlich nicht mehr dazu passt

2020-09-23 11:22 UTC, mgursch commented on {{cookiecutter.repo_name}}/buildSrc/src/main/kotlin/at/allaboutapps/build/Dependencies.kt
> +    const val KotlinReflect = "org.jetbrains.kotlin:kotlin-reflect:${Versions.Kotlin}"
Wieso benötigen wir das im Template Projekt?

2020-09-23 12:28 UTC, bleeding182 commented on {{cookiecutter.repo_name}}/.editorconfig
> +disabled_rules=import-ordering,no-wildcard-imports
Why are we disabling `no-wildcard-imports`?

2020-09-23 14:13 UTC, geworfener commented on {{cookiecutter.repo_name}}/app/build.gradle
> -        sourceCompatibility JavaVersion.VERSION_1_8
a) sourceCompatibility und targetCompatibility werden schon im build plugin entsprechend gesetzt
b) der (https://www.duden.de/rechtschreibung/Kommentar) kommentar bezieht sich auf die zeile, die stehen bleibt (coreLibraryDesugaringEnabled)

2020-09-23 14:15 UTC, bleeding182 commented on {{cookiecutter.repo_name}}/buildSrc/src/main/kotlin/at/allaboutapps/build/Dependencies.kt
> +    const val RetrofitAdapterRxJava = "com.squareup.retrofit2:adapter-rxjava3:${Versions.Retrofit}"
ich wuerde das eher noch bei den anderen hinzufuegen als hier wegnehmen, da wir ueber das naechste jahr eventuell noch in faelle laufen werden wo wir rxjava 2 & 3 gleichzeitig einbinden werden muessen

2020-09-23 14:21 UTC, mgursch commented on {{cookiecutter.repo_name}}/buildSrc/src/main/kotlin/at/allaboutapps/build/Dependencies.kt
> +    const val RetrofitAdapterRxJava = "com.squareup.retrofit2:adapter-rxjava3:${Versions.Retrofit}"
sehe ich auch so, bitte dann überall einfügen, damit man sofort erkennt was hier verwendet wird.

2020-09-23 14:48 UTC, geworfener commented on {{cookiecutter.repo_name}}/buildSrc/src/main/kotlin/at/allaboutapps/build/Dependencies.kt
> +    const val KotlinReflect = "org.jetbrains.kotlin:kotlin-reflect:${Versions.Kotlin}"
hat build warning, dass unterschiedliche versionen verwendet werden, behoben - wurde nun offenbar mit neuem gradle oder kotlin behoben - habs wieder entfernt!

2020-09-23 15:22 UTC, geworfener commented on {{cookiecutter.repo_name}}/buildSrc/src/main/kotlin/at/allaboutapps/build/Dependencies.kt
> +    const val KotlinReflect = "org.jetbrains.kotlin:kotlin-reflect:${Versions.Kotlin}"
hm, nein sync warning bleibt doch:
```
Runtime JAR files in the classpath should have the same version. These files were found in the classpath: /home/flo/.gradle/wrapper/dists/gradle-6.6.1-all/ejrtlte9hlw8v6ii20a9584rs/gradle-6.6.1/lib/kotlin-stdlib-1.3.72.jar (version 1.3) /home/flo/.gradle/wrapper/dists/gradle-6.6.1-all/ejrtlte9hlw8v6ii20a9584rs/gradle-6.6.1/lib/kotlin-stdlib-common-1.3.72.jar (version 1.3) /home/flo/.gradle/wrapper/dists/gradle-6.6.1-all/ejrtlte9hlw8v6ii20a9584rs/gradle-6.6.1/lib/kotlin-stdlib-jdk7-1.3.72.jar (version 1.3) /home/flo/.gradle/wrapper/dists/gradle-6.6.1-all/ejrtlte9hlw8v6ii20a9584rs/gradle-6.6.1/lib/kotlin-stdlib-jdk8-1.3.72.jar (version 1.3) /home/flo/.gradle/wrapper/dists/gradle-6.6.1-all/ejrtlte9hlw8v6ii20a9584rs/gradle-6.6.1/lib/kotlin-reflect-1.3.72.jar (version 1.3) /home/flo/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.4.0/e3765b66f0610afc92053ff1a93a87a544fca2b/kotlin-stdlib-jdk8-1.4.0.jar (version 1.4) /home/flo/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.4.0/aa2101a19d8688e368ae6e35e8967550ced73884/kotlin-reflect-1.4.0.jar (version 1.4) /home/flo/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.4.0/9cc187c3dfaf6e4001bdf962e3cdadff7690261b/kotlin-stdlib-jdk7-1.4.0.jar (version 1.4) /home/flo/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.4.0/63e75298e93d4ae0b299bb869cf0c627196f8843/kotlin-stdlib-1.4.0.jar (version 1.4) /home/flo/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.4.0/1c752cce0ead8d504ccc88a4fed6471fd83ab0dd/kotlin-stdlib-common-1.4.0.jar (version 1.4)
```

2021-02-10 16:30 UTC, bleeding182 approved these changes

2021-03-24 09:21 UTC, mgursch approved these changes

2021-03-24 09:21 UTC, merged