Update dependencies
allaboutapps/A3AndroidTemplate pull request #49
Opened 2021-08-09 13:55 UTC by Mani7K

2021-08-10 11:07 UTC, mgursch commented on {{cookiecutter.repo_name}}/buildSrc/src/main/kotlin/at/allaboutapps/build/Dependencies.kt
> +    const val OkHttp = "5.0.0-alpha.2"
Alpha Version würde ich hinterfragen (?)

2021-08-10 14:07 UTC, mgursch approved these changes
Aus meiner Sicht OK

2021-08-10 14:59 UTC, mfederczuk requested changes

2021-08-16 09:46 UTC, bleeding182 commented on {{cookiecutter.repo_name}}/buildSrc/src/main/kotlin/at/allaboutapps/build/Dependencies.kt
> +    const val Kotlin = "1.5.0"
auch in buildSrc gradle updaten (nicht nur dependencies)

2021-08-19 12:58 UTC, mgursch commented on {{cookiecutter.repo_name}}/buildSrc/src/main/kotlin/at/allaboutapps/build/Dependencies.kt
> +    const val Kotlin = "1.5.0"
@Mani7K  kannst das noch machen bitte?

2021-10-01 08:24 UTC, merged