Replace old splashscreen with androidx splashscreen
allaboutapps/A3AndroidTemplate pull request #62
Opened 2022-08-18 08:24 UTC by a3mani

Replace old SplashScreenHelper with androidx splash screen

2022-08-18 11:42 UTC, mgursch requested changes
installSplashScreen müsste irgendwo aufgerufen werden. Siehe Doku Punkt 3
https://developer.android.com/reference/kotlin/androidx/core/splashscreen/SplashScreen

2022-08-18 15:21 UTC, mgursch approved these changes

2022-08-22 08:06 UTC, mfederczuk commented
Wird der [`SplashScreenHelper`](https://github.com/allaboutapps/A3AndroidTemplate/blob/replace-splashcreen/%7B%7Bcookiecutter.repo_name%7D%7D/app/src/main/java/%7B%7Bcookiecutter.package_name_dir%7D%7D/application/SplashScreenHelper.kt) dann eigentlich noch gebraucht?  
Sollte ja die lib dann von selber auf den richtigen theme wechseln, oder nicht?

2022-08-22 08:10 UTC, mgursch commented
> Wird der [`SplashScreenHelper`](https://github.com/allaboutapps/A3AndroidTemplate/blob/replace-splashcreen/%7B%7Bcookiecutter.repo_name%7D%7D/app/src/main/java/%7B%7Bcookiecutter.package_name_dir%7D%7D/application/SplashScreenHelper.kt) dann eigentlich noch gebraucht? Sollte ja die lib dann von selber auf den richtigen theme wechseln, oder nicht?

SplashScreenHelper kann vollständig aus dem Projekt entfernt werden dann, ja

2022-08-29 06:43 UTC, mgursch approved these changes

2022-08-29 06:57 UTC, merged