Shared epoxy models
allaboutapps/A3AndroidTemplate pull request #67
Opened 2022-09-07 10:07 UTC by a3mani

2022-09-25 15:22 UTC, mfederczuk requested changes

2022-09-25 15:22 UTC, mfederczuk commented on {{cookiecutter.repo_name}}/sharedepoxymodels/src/main/java/at/allaboutapps/sharedepoxymodels/EmptyModel.kt
> +        if (icon != null) {
ich würd empfehlen als default/invalid wert `ResourcesCompat.ID_NULL` zu benutzen, dann muss man auch nicht den null assertion operator benutzen (`icon!!`)

2022-09-25 15:22 UTC, mfederczuk commented on {{cookiecutter.repo_name}}/sharedepoxymodels/src/main/java/at/allaboutapps/sharedepoxymodels/EmptyModel.kt
> +            holder.icon.isGone = true
Ich würd empfehlen `holder.icon.isVisible` außerhalb vom `if` zu machen, sodass wenn man einen weiteren branch dazu gibt, dass man nicht drauf vergessen kann. i.e.:

```kotlin
holder.icon.isVisible = (icon != null)
if(icon != null) {
    holder.icon.setImageResource(icon!!)
}
```

man könnte es auch so schreiben, um duplicate code zu vermeiden:

```kotlin
holder.icon.isVisible =
    if(icon != null) {
        holder.icon.setImageResource(icon!!)
        true
    } else {
        false
    }
```

2022-09-25 15:22 UTC, mfederczuk commented on {{cookiecutter.repo_name}}/sharedepoxymodels/src/main/res/layout/empty_model.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
`ConstraintLayout` vermeiden bei epoxy models, außerdem ist das ein sehr einfaches layout dass man ganz easy mit nem `LinearLayout` abbilden kann. Nicht zu kompliziert denken

2022-09-25 15:22 UTC, mfederczuk commented on {{cookiecutter.repo_name}}/sharedepoxymodels/src/main/res/layout/empty_model.xml
> +    <androidx.appcompat.widget.AppCompatImageView
Einfach normales `ImageView` verwenden

2022-09-25 15:22 UTC, mfederczuk commented on {{cookiecutter.repo_name}}/sharedepoxymodels/src/main/res/values/strings.xml
> +</resources>
Bin kein fan davon dass die strings im `:sharedepoxymodels` modul liegen, though mir fällt grad auch keine elegante Lösung ein.

Wenn man die texterify strings exported werden die hier nicht betroffen, und das kann zu ein paar bugs führen, also würd ichs besser finden wenn man die strings explizit angeben müsste, i.e.: keine defaults

2022-09-25 15:22 UTC, mfederczuk commented on {{cookiecutter.repo_name}}/sharedepoxymodels/src/main/java/at/allaboutapps/sharedepoxymodels/ErrorModel.kt
> +    inner class Holder : EpoxyHolder() {
ditto wie bei header und empty model

2022-09-25 15:22 UTC, mfederczuk commented on {{cookiecutter.repo_name}}/sharedepoxymodels/src/main/res/layout/error_model.xml
> +    <androidx.appcompat.widget.AppCompatImageView
`ImageView`

2022-09-25 15:22 UTC, mfederczuk commented on {{cookiecutter.repo_name}}/sharedepoxymodels/src/main/res/layout/error_model.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
`ConstraintLayout` → `LinearLayout`

2022-09-25 15:22 UTC, mfederczuk commented on {{cookiecutter.repo_name}}/sharedepoxymodels/src/main/res/layout/error_model.xml
> +        android:textAppearance="@style/TextAppearance.AppCompat.Header"
Theme attribute

2022-09-25 15:22 UTC, mfederczuk commented on {{cookiecutter.repo_name}}/sharedepoxymodels/src/main/res/layout/error_model.xml
> +        android:textAppearance="@style/TextAppearance.AppCompat.Body"
Theme attribute

2022-09-25 15:22 UTC, mfederczuk commented on {{cookiecutter.repo_name}}/sharedepoxymodels/src/main/java/at/allaboutapps/sharedepoxymodels/ErrorModel.kt
> +    @EpoxyAttribute @DrawableRes var icon: Int = R.drawable.ic_error
ditto wie bei empty model

2022-09-25 15:22 UTC, mfederczuk commented on {{cookiecutter.repo_name}}/sharedepoxymodels/src/main/res/layout/header_model.xml
> +    android:id="@+id/tvHeader"
Consistent mit den IDs bleiben — bei den meisten die jetzt geadded wurden wird keine hungarian notation benutzt, hier aber schon.
Schau was bei den anderen IDs, die's schon vor dem PR gab, benutzt wird.

2022-09-25 15:22 UTC, mfederczuk commented on {{cookiecutter.repo_name}}/sharedepoxymodels/src/main/res/layout/header_model.xml
> +<?xml version="1.0" encoding="utf-8"?>
File naming beachten; naming style für resource files ist immer `<type>_<name>.xml`.
Epoxy model layouts nennen auch immer `item` und nicht `model`.

Das, und die anderen layout files sollten also `item_(header|empty|loading|error).xml` heißen.

2022-09-25 15:22 UTC, mfederczuk commented on {{cookiecutter.repo_name}}/sharedepoxymodels/src/main/res/values/styles.xml
> +<?xml version="1.0" encoding="utf-8"?>
Das file sollte eigentlich nicht in dem modul sein, sondern in `:app`.

2022-09-25 15:33 UTC, mfederczuk commented
Noch was: ich find der package name sollte nicht `at.allaboutapps` sein, sondern da sollte die template variable benutzt werden: `{{ cookiecutter.package_name }}`

2023-08-28 10:57 UTC, markusgursch-aaa commented
Ich würd mal sagen, diesen PR kann man verwerfen - brauchen wir nicht mehr

2023-09-25 06:07 UTC, closed without merging