force update
allaboutapps/A3AndroidTemplate pull request #75
Opened 2023-07-14 08:40 UTC by geworfener

2023-07-17 08:32 UTC, bleeding182 commented on {{cookiecutter.repo_name}}/config/src/main/java/{{cookiecutter.package_name_dir}}/config/data/ConfigRepo.kt
> +        private const val PREF_VALUE_DEFAULT_MINIMUM_VERSION_CODE = -1L
we could just use `1` here as this is the lowest valid verison code

2023-07-17 08:32 UTC, bleeding182 commented on {{cookiecutter.repo_name}}/config/src/main/java/{{cookiecutter.package_name_dir}}/config/data/ConfigRepo.kt
> +        .map {
method reference? or name `it`

2023-07-17 08:32 UTC, bleeding182 commented on {{cookiecutter.repo_name}}/config/src/main/java/{{cookiecutter.package_name_dir}}/config/data/ConfigRepo.kt
> +            val minSupportedVersionCode = loadStoredConfig()
all this could be simplified to `fromCallable { pref.getLong() }`

2023-07-17 08:32 UTC, bleeding182 commented on {{cookiecutter.repo_name}}/config/build.gradle.kts
> +        sourceDirs.addAll(files("build/generated/source/kapt/main", "build/generated/source/kaptKotlin/main"))
I believe all this idea workaround should no longer be necessary

2023-07-17 08:32 UTC, bleeding182 commented on {{cookiecutter.repo_name}}/app/src/main/java/{{cookiecutter.package_name_dir}}/features/forceupdate/ForceUpdateCheckerCallback.kt
> +                if (BuildConfig.VERSION_CODE < config.minSupportedVersionCode) {
we should not depend on `BuildConfig` and i believe the module here can't even access it either

read the real value from context, drop the buildConfig

2023-07-17 08:32 UTC, bleeding182 commented on {{cookiecutter.repo_name}}/app/src/main/java/{{cookiecutter.package_name_dir}}/features/forceupdate/ForceUpdateCheckerCallback.kt
> +        val disposable = configRepo.config()
we should still properly dispose in stop, even though it's unlikely that it'll take that long

2023-07-17 08:32 UTC, bleeding182 commented on {{cookiecutter.repo_name}}/app/src/main/AndroidManifest.xml
> +            android:name=".features.forceupdate.ForceUpdateActivity"
singletop for good measure?

2023-07-20 07:41 UTC, geworfener commented on {{cookiecutter.repo_name}}/config/src/main/java/{{cookiecutter.package_name_dir}}/config/data/ConfigRepo.kt
> +        private const val PREF_VALUE_DEFAULT_MINIMUM_VERSION_CODE = -1L
keeping -1 for now, so we can differentiate between "not set" and version code 1

2023-08-03 15:14 UTC, bleeding182 requested changes
We should use Long for version codes since int has been deprecated some versions ago

2023-08-03 15:14 UTC, bleeding182 commented on {{cookiecutter.repo_name}}/config/src/main/java/{{cookiecutter.package_name_dir}}/config/data/Config.kt
> +    val minSupportedVersionCode: Int,
versioncode should be a long?

2023-08-03 15:14 UTC, bleeding182 commented on {{cookiecutter.repo_name}}/config/src/main/java/{{cookiecutter.package_name_dir}}/config/usecase/ForceUpdateCheckerUseCase.kt
> +        packageInfo.versionCode
deprecated? use longVersionCode on newer versions, this as fallback

2023-08-08 09:40 UTC, geworfener commented on {{cookiecutter.repo_name}}/config/src/main/java/{{cookiecutter.package_name_dir}}/config/usecase/ForceUpdateCheckerUseCase.kt
> +        packageInfo.versionCode
I wasn't sure first and did not check because I thought we would never need this, but yes this is completely backwards compatible, so we could just use longVersionCode without any fallback

2023-08-08 09:40 UTC, geworfener commented on {{cookiecutter.repo_name}}/config/src/main/java/{{cookiecutter.package_name_dir}}/config/data/Config.kt
> +    val minSupportedVersionCode: Int,
requires api level 28, current min is 26..

2023-08-09 13:34 UTC, bleeding182 approved these changes

2023-08-10 07:31 UTC, merged